markdown: kramdown
highlighter: rouge
sass:
  style: compressed

repository: https://github.com/jallenwork/pages-theme

timezone: America/New_York

defaults:
  -
    scope:
      path: "_docs"
      type: "docs"
    values:
      layout: "docs"
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "news_item"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /news/:year/:month/:day/:title/
    output: true

title: Site Docs
name: Some Name
description: A theme for pages documentation
url: https://github.com

logo: /img/logo-2x.png

exclude:
  - .gitignore
  - README.md
